access-token: f02d8fafb522303d8efc762bf9bfe9b44a9b1dcdf05a7f8bfcbfbeb8be74b791
account.get.format: ""
account.get.no-header: false
account.ratelimit.format: ""
account.ratelimit.no-header: false
action.get.format: ""
action.get.no-header: false
action.list.action-type: ""
action.list.after: ""
action.list.before: ""
action.list.format: ""
action.list.no-header: false
action.list.region: ""
action.list.resource-type: ""
action.list.status: ""
action.wait.format: ""
action.wait.no-header: false
action.wait.poll-timeout: 5
compute.ssh.ssh-agent-forwarding: false
compute.ssh.ssh-key-path: /home/michael/.ssh/glaux-web
compute.ssh.ssh-port: 5493
compute.ssh.ssh-private-ip: false
compute.ssh.ssh-user: glaux
domain.create.format: ""
domain.create.ip-address: ""
domain.create.ip-address.required: true
domain.create.no-header: false
domain.get.format: ""
domain.get.no-header: false
domain.list.format: ""
domain.list.no-header: false
droplet-action.change-kernel.format: ""
droplet-action.change-kernel.kernel-id: 0
droplet-action.change-kernel.kernel-id.required: true
droplet-action.change-kernel.no-header: false
droplet-action.change-kernel.wait: false
droplet-action.disable-backups.format: ""
droplet-action.disable-backups.no-header: false
droplet-action.disable-backups.wait: false
droplet-action.enable-ipv6.format: ""
droplet-action.enable-ipv6.no-header: false
droplet-action.enable-ipv6.wait: false
droplet-action.enable-private-networking.format: ""
droplet-action.enable-private-networking.no-header: false
droplet-action.enable-private-networking.wait: false
droplet-action.get.action-id: 0
droplet-action.get.action-id.required: true
droplet-action.get.format: ""
droplet-action.get.no-header: false
droplet-action.password-reset.format: ""
droplet-action.password-reset.no-header: false
droplet-action.password-reset.wait: false
droplet-action.power-cycle.format: ""
droplet-action.power-cycle.no-header: false
droplet-action.power-cycle.wait: false
droplet-action.power-off.format: ""
droplet-action.power-off.no-header: false
droplet-action.power-off.wait: false
droplet-action.power-on.format: ""
droplet-action.power-on.no-header: false
droplet-action.power-on.wait: false
droplet-action.reboot.format: ""
droplet-action.reboot.no-header: false
droplet-action.reboot.wait: false
droplet-action.rebuild.format: ""
droplet-action.rebuild.image: ""
droplet-action.rebuild.image.required: true
droplet-action.rebuild.no-header: false
droplet-action.rebuild.wait: false
droplet-action.rename.droplet-name: ""
droplet-action.rename.droplet-name.required: true
droplet-action.rename.format: ""
droplet-action.rename.no-header: false
droplet-action.rename.wait: false
droplet-action.resize.format: ""
droplet-action.resize.no-header: false
droplet-action.resize.resize-disk: false
droplet-action.resize.size: ""
droplet-action.resize.wait: false
droplet-action.restore.format: ""
droplet-action.restore.image-id: 0
droplet-action.restore.image-id.required: true
droplet-action.restore.no-header: false
droplet-action.restore.wait: false
droplet-action.shutdown.format: ""
droplet-action.shutdown.no-header: false
droplet-action.shutdown.wait: false
droplet-action.snapshot.format: ""
droplet-action.snapshot.no-header: false
droplet-action.snapshot.snapshot-name: ""
droplet-action.snapshot.snapshot-name.required: true
droplet-action.snapshot.wait: false
droplet-action.upgrade.format: ""
droplet-action.upgrade.no-header: false
droplet-action.upgrade.wait: false
droplet.actions.format: ""
droplet.actions.no-header: false
droplet.backups.format: ""
droplet.backups.no-header: false
droplet.create.enable-backups: false
droplet.create.enable-ipv6: false
droplet.create.enable-private-networking: false
droplet.create.format: ""
droplet.create.image: ""
droplet.create.image.required: true
droplet.create.no-header: false
droplet.create.region: ""
droplet.create.region.required: true
droplet.create.size: ""
droplet.create.size.required: true
droplet.create.ssh-keys: '[]'
droplet.create.tag-name: ""
droplet.create.user-data: ""
droplet.create.user-data-file: ""
droplet.create.volumes: '[]'
droplet.create.wait: false
droplet.delete.force: false
droplet.get.format: ""
droplet.get.no-header: false
droplet.kernels.format: ""
droplet.kernels.no-header: false
droplet.list.format: ""
droplet.list.no-header: false
droplet.list.region: ""
droplet.list.tag-name: ""
droplet.neighbors.format: ""
droplet.neighbors.no-header: false
droplet.snapshots.format: ""
droplet.snapshots.no-header: false
droplet.tag.tag-name: ""
droplet.tag.tag-name.required: true
droplet.untag.tag-name: '[]'
enable-beta: null
floating-ip-action.assign.format: ""
floating-ip-action.assign.no-header: false
floating-ip-action.get.format: ""
floating-ip-action.get.no-header: false
floating-ip-action.unassign.format: ""
floating-ip-action.unassign.no-header: false
floating-ip.create.droplet-id: 0
floating-ip.create.format: ""
floating-ip.create.no-header: false
floating-ip.create.region: ""
floating-ip.get.format: ""
floating-ip.get.no-header: false
floating-ip.list.format: ""
floating-ip.list.no-header: false
floating-ip.list.region: ""
image-action.get.action-id: 0
image-action.get.action-id.required: true
image-action.get.format: ""
image-action.get.no-header: false
image-action.transfer.format: ""
image-action.transfer.no-header: false
image-action.transfer.region: ""
image-action.transfer.region.required: true
image-action.transfer.wait: false
image.get.format: ""
image.get.no-header: false
image.list-application.format: ""
image.list-application.no-header: false
image.list-application.public: false
image.list-distribution.format: ""
image.list-distribution.no-header: false
image.list-distribution.public: false
image.list-user.format: ""
image.list-user.no-header: false
image.list-user.public: false
image.list.format: ""
image.list.no-header: false
image.list.public: false
image.update.format: ""
image.update.image-name: ""
image.update.image-name.required: true
image.update.no-header: false
output: text
records.create.format: ""
records.create.no-header: false
records.create.record-data: ""
records.create.record-name: ""
records.create.record-port: 0
records.create.record-priority: 0
records.create.record-type: ""
records.create.record-weight: 0
records.list.domain-name: ""
records.list.format: ""
records.list.no-header: false
records.update.format: ""
records.update.no-header: false
records.update.record-data: ""
records.update.record-id: 0
records.update.record-name: ""
records.update.record-port: 0
records.update.record-priority: 0
records.update.record-type: ""
records.update.record-weight: 0
region.list.format: ""
region.list.no-header: false
size.list.format: ""
size.list.no-header: false
ssh-key.create.format: ""
ssh-key.create.no-header: false
ssh-key.create.public-key: ""
ssh-key.create.public-key.required: true
ssh-key.get.format: ""
ssh-key.get.no-header: false
ssh-key.import.format: ""
ssh-key.import.no-header: false
ssh-key.import.public-key-file: ""
ssh-key.import.public-key-file.required: true
ssh-key.list.format: ""
ssh-key.list.no-header: false
ssh-key.update.format: ""
ssh-key.update.key-name: ""
ssh-key.update.key-name.required: true
ssh-key.update.no-header: false
tag.update.tag-name: ""
tag.update.tag-name.required: true
volume.create.desc: ""
volume.create.format: ""
volume.create.no-header: false
volume.create.region: ""
volume.create.region.required: true
volume.create.size: 4TiB
volume.create.size.required: true
volume.get.format: ""
volume.get.no-header: false
volume.list.format: ""
volume.list.no-header: false
