#! perl

#Simply place the scripts you want to install in /usr/lib/urxvt/perl/ for system-wide availability or in ~/.urxvt/ext/ for user-only availability. You can also put them in a folder of your choice, but then you have to add this line to your .Xdefaults/.Xresources:
#URxvt.perl-lib: /your/folder/

# then add
# URxvt.perl-ext-common: on_osc_seq_perl


sub on_osc_seq_perl {
  my ($term, $osc, $resp) = @_;
  if ($osc =~ /^notify;(\S+);(.*)$/) {
    system("notify-send '$1' '$2'");
    system("aplay ~/.dotfiles/files/soft_beep.way")
  }
}


# can be run with tmux
# Support passing through escape sequences to the underlying terminal by
# using DCS with a "tmux;" prefix. Escape characters in the sequences must
# be doubled. For example:
#
# $ printf '\033Ptmux;\033\033]12;red\007\033\\'
#
# alias alert="echo -ne '\033Ptmux;\033\033]777;notify;$(hostname);$(date '+%Y-%m-%d %H:%M:%S');Computation completed!;\007\007\\033\\'"
