#!/bin/sh

# cloud config
sed -i -e '$a127.0.0.1    faz.net' /etc/hosts
sed -i -e '$a127.0.0.1    www.faz.net' /etc/hosts
sed -i -e '$a127.0.0.1    m.faz.net' /etc/hosts
sed -i -e '$a127.0.0.1    sueddeutsche.de' /etc/hosts
sed -i -e '$a127.0.0.1    www.sueddeutsche.de' /etc/hosts
crontab -l 2>/dev/null; echo "0 4 * * * /sbin/shutdown -r +5" | crontab -
